package rashjz.info.app.bp.domain;
// Generated Aug 19, 2016 3:16:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GcmUsers generated by hbm2java
 */
public class GcmUsers  implements java.io.Serializable {


     private Integer id;
     private String gcmRegid;
     private String name;
     private String email;
     private Date createdAt;
     private String status;

    public GcmUsers() {
    }

	
    public GcmUsers(Date createdAt) {
        this.createdAt = createdAt;
    }
    public GcmUsers(String gcmRegid, String name, String email, Date createdAt, String status) {
       this.gcmRegid = gcmRegid;
       this.name = name;
       this.email = email;
       this.createdAt = createdAt;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGcmRegid() {
        return this.gcmRegid;
    }
    
    public void setGcmRegid(String gcmRegid) {
        this.gcmRegid = gcmRegid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


