package rashjz.info.app.bp.domain;
// Generated Aug 19, 2016 3:16:01 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Location generated by hbm2java
 */
//@JsonIgnoreProperties(ignoreUnknown = true)
public class Location implements java.io.Serializable {
//
//    @JsonView(Views.Public.class)
    private Integer recId;
    
//    @JsonView(Views.Public.class)
    private String title;

//    @JsonView(Views.Public.class)
    private String note;
    
//    @JsonView(Views.Public.class)
    private Date insDate;
    
//    @JsonView(Views.Public.class)
    private String status;
    
//    @JsonView(Views.Public.class)
    private Float latitude;
    
//    @JsonView(Views.Public.class)
    private Float longitude;

    public Location() {
    }

    public Location(Date insDate) {
        this.insDate = insDate;
    }

    public Location(String title, String note, Date insDate, String status, Float latitude, Float longitude) {
        this.title = title;
        this.note = note;
        this.insDate = insDate;
        this.status = status;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Integer getRecId() {
        return this.recId;
    }

    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Date getInsDate() {
        return this.insDate;
    }

    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Float getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    public Float getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

}
