package rashjz.info.app.bp.domain;
// Generated Aug 19, 2016 3:16:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersistentLogins generated by hbm2java
 */
public class PersistentLogins  implements java.io.Serializable {


     private String series;
     private String username;
     private String token;
     private Date lastUsed;

    public PersistentLogins() {
    }

    public PersistentLogins(String series, String username, String token, Date lastUsed) {
       this.series = series;
       this.username = username;
       this.token = token;
       this.lastUsed = lastUsed;
    }
   
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getLastUsed() {
        return this.lastUsed;
    }
    
    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }




}


