package rashjz.info.app.bp.domain;
// Generated Aug 19, 2016 3:16:01 PM by Hibernate Tools 4.3.1



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer roleId;
     private String name;

    public Role() {
    }

    public Role(String name) {
       this.name = name;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


