package rashjz.info.app.bp.domain;
// Generated Aug 19, 2016 3:16:01 PM by Hibernate Tools 4.3.1



/**
 * VoteContent generated by hbm2java
 */
public class VoteContent  implements java.io.Serializable {


     private Integer recId;
     private Float value;
     private Integer contentId;
     private String macId;
     private Integer voteType;

    public VoteContent() {
    }

    public VoteContent(Float value, Integer contentId, String macId, Integer voteType) {
       this.value = value;
       this.contentId = contentId;
       this.macId = macId;
       this.voteType = voteType;
    }
   
    public Integer getRecId() {
        return this.recId;
    }
    
    public void setRecId(Integer recId) {
        this.recId = recId;
    }
    public Float getValue() {
        return this.value;
    }
    
    public void setValue(Float value) {
        this.value = value;
    }
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }
    public String getMacId() {
        return this.macId;
    }
    
    public void setMacId(String macId) {
        this.macId = macId;
    }
    public Integer getVoteType() {
        return this.voteType;
    }
    
    public void setVoteType(Integer voteType) {
        this.voteType = voteType;
    }




}


