CREATE TABLE APP_NEWS
(
    REC_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(95),
    CONTENT VARCHAR(745),
    INS_DATE DATETIME NOT NULL,
    IMG VARCHAR(95),
    VIDEO VARCHAR(45),
    HIT_COUNT INT(11),
    NOTE VARCHAR(45),
    STATUS VARCHAR(3)
);
CREATE UNIQUE INDEX REC_ID_UNIQUE ON APP_NEWS (REC_ID);
CREATE TABLE CONTENT
(
    REC_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(300),
    DESCRIPTION VARCHAR(5800),
    RELEASE_YEAR INT(11),
    RATING FLOAT(8,4),
    END_DATE DATE,
    INS_DATE DATE,
    VIDEO_URL VARCHAR(200),
    IMG_URL VARCHAR(200),
    LOCATION_ID INT(11),
    GENRE VARCHAR(200),
    NOTE VARCHAR(1000),
    STATUS VARCHAR(1),
    TYPE_ID INT(11),
    AGE_ALLOW INT(11),
    PRICE FLOAT(8,4),
    PRODUCER VARCHAR(200),
    WRITER VARCHAR(100)
);
CREATE INDEX indexDateEnd ON CONTENT (END_DATE);
CREATE TABLE CONTENT_COMMENTS
(
    REC_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DEVICE_MAC_ID VARCHAR(100),
    CONTENT_ID INT(11),
    USER_COMMENT VARCHAR(3000),
    STATUS VARCHAR(1),
    USER_EMAIL VARCHAR(40),
    ins_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE CONTENT_TYPE
(
    TYPE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(200)
);
CREATE TABLE GCM_USERS
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    GCM_REGID VARCHAR(1000),
    NAME VARCHAR(100),
    EMAIL VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS VARCHAR(20)
);
CREATE TABLE LOCATION
(
    REC_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(300),
    NOTE VARCHAR(1000),
    INS_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS VARCHAR(1),
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);
CREATE TABLE persistent_logins
(
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) PRIMARY KEY NOT NULL,
    token VARCHAR(64) NOT NULL,
    last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE ROLE
(
    ROLE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL
);
CREATE TABLE user_roles
(
    user_role_id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(45) NOT NULL,
    role VARCHAR(45) NOT NULL,
    CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username)
);
CREATE INDEX fk_username_idx ON user_roles (username);
CREATE UNIQUE INDEX uni_username_role ON user_roles (role, username);
CREATE TABLE users
(
    username VARCHAR(45) PRIMARY KEY NOT NULL,
    password VARCHAR(45) NOT NULL,
    enabled TINYINT(4) DEFAULT '1' NOT NULL,
    firstname VARCHAR(105),
    lastname VARCHAR(145),
    note VARCHAR(245)
);
CREATE TABLE VOTE_CONTENT
(
    REC_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    VALUE FLOAT(8,4),
    CONTENT_ID INT(11),
    MAC_ID VARCHAR(200),
    VOTE_TYPE INT(11)
);
CREATE TABLE VOTE_TYPE
(
    TYPE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100)
);